name: 'support_ticket_rag'
version: '1.0.0'
config-version: 2

profile: 'support_ticket_rag'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  support_ticket_rag:
    staging:
      +materialized: view
    marts:
      +materialized: table
